repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami

releases:
- name: kafka1
  namespace: prod
  version: 25.3.5
  chart: bitnami/kafka
  set:
  - name: image.tag
    value: 3.5.2
  - name: broker.replicaCount
    value: 5
  - name: listeners.client.protocol
    value: SASL_PLAINTEXT
  - name: listeners.interbroker.protocol
    value: SASL_PLAINTEXT
- name: kafka2
  namespace: dev
  chart: bitnami/kafka
  set:
  - name: controller.replicaCount
    value: 1
  - name: broker.replicaCount
    value: 1
  - name: listeners.client.protocol
    value: PLAINTEXT
  - name: listeners.interbroker.protocol
    value: PLAINTEXT
