---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: custom-access
rules:
  - apiGroups: ["*"]
    resources: ["mysqls", "deployments"]
    verbs: ["*"]
  - apiGroups: ["*"]
    resources: ["services", "persistentvolumes", "persistentvolumeclaims"]
    verbs: ["create", "delete", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: custom-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: custom-access
subjects:
- kind: ServiceAccount
  name: api-adm
  namespace: default