apiVersion: v1
kind: Pod
metadata:
  name: practice1
  namespace: homework
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    command: ['sh', '-c', "sed -i 's#root   /usr/share/nginx/html;#root   /homework;#g' /etc/nginx/conf.d/default.conf && \
      sed -i 's#listen       80;#listen       8000;#g' /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]
    ports:
    - containerPort: 8000
    volumeMounts:
    - name: workdir
      mountPath: /homework
    lifecycle:
      preStop:
          exec:
            command: ["/bin/sh","-c","rm -f /homework/index.html"]
  initContainers:
  - name: init
    image: busybox:1.28
    command: ['wget', 'https://otus.ru', '-O', '/init/index.html']
    volumeMounts:
    - name: workdir
      mountPath: /init
  volumes:
  - name: workdir
    emptyDir: {}
