apiVersion: "monitoring.coreos.com/v1"
kind: ServiceMonitor
metadata:
  name: hw-nginx
  namespace: default
  finalizers: []
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  endpoints:
    - port: exporter
      path: /metrics


