---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.cm_nginx }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
data:
  default.conf: |
    server {
        listen       8000 default_server;
        server_name  _;

        default_type text/plain;

        location / {
            root   /homework;
            index  index.html index.htm;
        }

        location /homepage {
            return 200 "Rewrite is work!";
        }

        error_page  404         /404.html;
    }
  