apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{ .Values.ing.host }}
    http:
      paths:
      - path: "/"
        pathType: Prefix      
        backend:
          service:
            name: {{ .Values.svc.name }}
            port:
              number: {{ .Values.svc.targ_port }}
