---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.pvc.name }}
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.sc }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.request }}

