apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.sa_cd }}
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.sa_cd }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: {{ .Values.sa_cd }}
  apiGroup: rbac.authorization.k8s.io