apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.svc.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.svc.port }}
    targetPort: {{ .Values.svc.targ_port }}
  selector:
    app: {{ .Chart.Name }}
  type: ClusterIP