apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.sc }}
  namespace: {{ .Values.namespace }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - discard
volumeBindingMode: Immediate
parameters:
  guaranteedReadWriteLatency: "true"