apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cd
  namespace: homework
subjects:
  - kind: ServiceAccount
    name: cd
    namespace: homework
roleRef:
  kind: Role
  name: hw_adm
  apiGroup: rbac.authorization.k8s.io