---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-secret-store
  namespace: vault
spec:
  provider:
    vault:
      server: "http://vault.vault:8200"
      path: "otus"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "otus"
          serviceAccountRef:
            name: "vault-auth"
            namespace: "vault"

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-secret
  namespace: vault  
spec:
  refreshInterval: "5s"
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: otus-cred
  data:
  - secretKey: username
    remoteRef:
      key: otus/cred
      property: username
  - secretKey: password
    remoteRef:
      key: otus/cred
      property: password