
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mysqls.kopf.dev
spec:
  scope: Namespaced
  group: kopf.dev
  names:
    kind: MySQL
    plural: mysqls
    singular: mysql
    shortNames:
      - mysqls
      - mysql
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true