---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "pvc-{name}"
  annotations:
    volume.beta.kubernetes.io/storage-class: standard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{storage_size}"